name: Monitor kubectl Provider

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor-provider:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        
    - name: Run provider monitoring
      run: |
        ./scripts/monitor-kubectl-provider.sh
        
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: kubectl-provider-report
        path: kubectl-provider-report-*.md
        
    - name: Create issue for new version
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const reportFiles = fs.readdirSync('.').filter(f => f.startsWith('kubectl-provider-report-'));
          
          if (reportFiles.length > 0) {
            const reportContent = fs.readFileSync(reportFiles[0], 'utf8');
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔍 kubectl Provider Update Available',
              body: `## kubectl Provider Monitoring Alert
              
              A new version of the \`alekc/kubectl\` provider is available.
              
              \`\`\`
              ${reportContent}
              \`\`\`
              
              **Action Required:**
              1. Review the compatibility report
              2. Test the new version in development
              3. Update provider version if compatible
              4. Update documentation
              
              **Critical:** This provider is essential for the educates platform module. Any updates must be thoroughly tested.
              
              ---
              *This issue was automatically generated by the kubectl provider monitoring workflow.*`,
              labels: ['provider-update', 'kubectl', 'monitoring']
            });
          }
